{% set name = "google-cloud-bigquery" %}
{% set version = "3.26.0" %}
{% set build = 0 %}
{% set sha256 = "edbdc788beea659e04c0af7fe4dcd6d9155344b98951a0d5055bd2f15da4ba23" %}
{% set dev_url = "https://github.com/googleapis/python-bigquery" %}
{% set doc_url = "https://googleapis.dev/python/bigquery/latest/index.html" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

outputs:
  - name: {{ name }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('google-cloud-bigquery-core', exact=True) }}
        # restricting to python >=3.8 to avoid dependency on importlib_metadata for python <3.8
        - python >=3.8
        # bqstorage and pandas extras
        - pyarrow >=3.0.0
        # bqstorage extra
        - google-cloud-bigquery-storage >=2.6.0,<3.0.0dev
        # going with the more restrictive constraint here so we can stay noarch
        - grpcio >=1.49.1,< 2.0dev
        # pandas extra
        - pandas >=1.1.0
        - db-dtypes >=0.3.0,<2.0.0dev
        # ipywidgets extra
        - ipywidgets >=7.7.0
        - ipykernel >=6.0.0
        # geopandas extra
        - geopandas >=0.9.0,<1.0dev
        - shapely >=1.8.4,<3.0.0dev
        # ipython extra
        - bigquery-magics >=0.1.0
        # tqdm extra
        - tqdm >=4.7.4,<=5.0.0dev
        # bigquery_v2 extra
        - proto-plus >=1.22.3,<2.0.0dev
        - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

    test:
      requires:
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.magics
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - pip check

  - name: {{ name }}-core
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools
      run:
        - python >=3.8
        - google-api-core-grpc >=2.11.1,<3.0.0dev
        - google-auth >=2.14.1,<3.0.0dev
        - google-cloud-core >=2.4.1,<3.0.0dev
        - google-resumable-media >=2.0.0,<3.0dev
        - packaging >=20.0.0
        - python-dateutil >=2.7.3,<3.0dev
        - requests >=2.21.0,<3.0.0dev

    test:
      requires:
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
      commands:
        - pip check

about:
  home: {{ dev_url }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery API client library
  doc_url: {{ doc_url }}
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - chalmerlowe
    - xylar
    - parthea
    - tswast
