{% set name = "google-cloud-bigquery" %}
{% set version = "2.1.0" %}
{% set sha256 = "7369e2f81ccddfa62f2af4009dbddf7a1daaef0fc701a4097e8de5508235af74" %}
{% set dev_url = "https://github.com/googleapis/python-bigquery" %}
{% set doc_url = "https://googleapis.dev/python/bigquery/latest/index.html" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Conda package for protobuf does not support Python 2.7 on Windows due to
  # requirement on C++ 11. VS 2008 is not supported.
  skip: true  # [win and vc<14]

requirements:
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      number: 0
      noarch: python

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - {{ name }}-core {{ version }}
        - python
        - google-cloud-bigquery-storage
        - ipython
        - pandas
        - pyarrow
        - tqdm

    test:
      requires:
        - python
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.magics
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - python -m pip check

    about:
      home: {{ dev_url }}
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Batteries-included library for BigQuery API
      description: |
        {{ name }} installs {{ name }}-core and the extra requirements for
        pandas and pyarrow integrations.

        Supported Python Versions
        -------------------------
        Python >= 3.6

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python == 3.5.

        The last version of this library compatible with Python 2.7 and
        3.5 is google-cloud-bigquery==1.28.0.
      doc_url: {{ doc_url }}
      dev_url: {{ dev_url }}

  - name: {{ name }}-core
    build:
      number: 0
      noarch: python
      script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

    requirements:
      host:
        - python
        - pip >=18.1
        - setuptools >=34.0.0

      run:
        - python
        - google-api-core-grpc >=1.22.2,<2.0.0dev
        - proto-plus >=1.10.0
        - libcst >=0.2.5
        - google-cloud-core >=1.4.1,<2.0.0dev
        - google-resumable-media >=0.6.0,<2.0dev
        - six >=1.13.0,<2.0.0dev
      run-constrained:
        - google-cloud-bigquery-storage-core >=2.0.0,<3.0.0dev
        - grpcio >=1.32.0,<2.0dev
        - pyarrow >=1.0.0,<2.0dev
        - ipython >=5.0.0
        - pandas >=0.23.0
        - tqdm >=4.7.4,<=5.0.0dev

    test:
      requires:
        - python
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - python -m pip check

    about:
      home: {{ dev_url }}
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: Core library for BigQuery API
      description: |
        {{ name }}-core the core client library for connecting to the BigQuery API.

        Supported Python Versions
        -------------------------
        Python >= 3.6

        Deprecated Python Versions
        --------------------------
        Python == 2.7, Python == 3.5.

        The last version of this library compatible with Python 2.7 and
        3.5 is google-cloud-bigquery==1.28.0.
      doc_url: {{ doc_url }}
      dev_url: {{ dev_url }}

about:
  home: {{ dev_url }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery API client library
  doc_url: {{ doc_url }}
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - leahecole
    - parthea
    - tswast
