{% set name = "google-cloud-bigquery" %}
{% set version = "3.38.0" %}
{% set build = 0 %}
{% set sha256 = "8afcb7116f5eac849097a344eb8bfda78b7cfaae128e60e019193dd483873520" %}
{% set dev_url = "https://github.com/googleapis/python-bigquery" %}
{% set doc_url = "https://googleapis.dev/python/bigquery/latest/index.html" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

outputs:
  - name: {{ name }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - {{ pin_subpackage('google-cloud-bigquery-core', exact=True) }}
        - python >={{ python_min }}
        # bqstorage and pandas extras
        - pyarrow >=4.0.0
        # bqstorage extra
        - google-cloud-bigquery-storage >=2.6.0,<3.0.0
        # going with the more restrictive (py >= 3.11) constraint here so we can stay noarch
        - grpcio >=1.49.1,<2.0.0
        # pandas extra
        - pandas >=1.3.0
        - pandas-gbq >=0.26.1
        - db-dtypes >=1.0.4,<2.0.0
        # ipywidgets extra
        - ipywidgets >=7.7.1
        - ipykernel >=6.2.0
        # geopandas extra
        - geopandas >=0.9.0,<2.0.0
        - shapely >=1.8.4,<3.0.0
        # ipython extra
        - bigquery-magics >=0.6.0
        # leaving out the matplotlib extra for now because it doesn't
        # work with python 3.9 unless we move away from noarch: python
        # - matplotlib-base >=3.7.1,<=3.9.2  # [py<310]
        # - matplotlib-base >=3.10.3  # [py>=310]
        # tqdm extra
        - tqdm >=4.23.4,<5.0.0
        # opentelemetry extra
        - opentelemetry-api >=1.1.0
        - opentelemetry-sdk >=1.1.0
        - opentelemetry-instrumentation >=0.20b0
        # bigquery_v2 extra
        - proto-plus >=1.22.3,<2.0.0
        - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.magics
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - pip check

  - name: {{ name }}-core
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - google-api-core-grpc >=2.11.1,<3.0.0
        - google-auth >=2.14.1,<3.0.0
        - google-cloud-core >=2.4.1,<3.0.0
        - google-resumable-media >=2.0.0,<3.0.0
        - packaging >=20.0.0
        - python-dateutil >=2.7.3,<3.0.0
        - requests >=2.21.0,<3.0.0

    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
      commands:
        - pip check

about:
  home: {{ dev_url }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery API client library
  doc_url: {{ doc_url }}
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - chalmerlowe
    - xylar
    - parthea
    - tswast
