{% set name = "google-cloud-bigquery" %}
{% set version = "3.2.0" %}
{% set build = 0 %}
{% set sha256 = "97fb4306e324cb86909ce32a9944e81d21fbcb28a780c5cdf01b6e4d47d4c322" %}
{% set dev_url = "https://github.com/googleapis/python-bigquery" %}
{% set doc_url = "https://googleapis.dev/python/bigquery/latest/index.html" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

outputs:
  - name: {{ name }}
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - {{ pin_subpackage('google-cloud-bigquery-core', exact=True) }}
        - python >=3.6
        - pandas >=1.0.0
        - db-dtypes >=0.3.0,<2.0.0dev
        - geopandas >=0.9.0,<1.0dev
        - shapely >=1.6.0,<2.0dev
        - ipython >=7.0.1,!=8.1.0
        - tqdm >=4.7.4,<=5.0.0dev

    test:
      requires:
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.magics
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - pip check

  - name: {{ name }}-core
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - grpcio >=1.38.1,<2.0dev
        - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
        - google-cloud-bigquery-storage-core >=2.0.0,<3.0.0dev
        - proto-plus >=1.15.0
        - google-cloud-core >=1.4.1,<3.0.0dev
        - google-resumable-media >=0.6.0,<3.0dev
        - packaging >=14.3
        - protobuf >=3.12.0
        - python-dateutil >=2.7.2,<3.0dev
        - pyarrow >=3.0.0,<9.0dev
        - requests >=2.18.0,<3.0.0dev

    test:
      requires:
        - pip
      imports:
        - google.api_core
        - google.cloud.bigquery
        - google.cloud.bigquery.client
        - google.cloud.bigquery.dataset
        - google.cloud.bigquery.encryption_configuration
        - google.cloud.bigquery.enums
        - google.cloud.bigquery.external_config
        - google.cloud.bigquery.job
        - google.cloud.bigquery.model
        - google.cloud.bigquery.query
        - google.cloud.bigquery.retry
        - google.cloud.bigquery.routine
        - google.cloud.bigquery.schema
        - google.cloud.bigquery.table
        - google.cloud.bigquery_v2
        - google.cloud.bigquery_v2.types
      commands:
        - pip check

about:
  home: {{ dev_url }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery API client library
  doc_url: {{ doc_url }}
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - xylar
    - parthea
    - tswast
